version: "3.8"

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - APP_HOST=app
      - APP_PORT=${APP_PORT}

  app:
    container_name: app
    build:
      context: ../../.
      dockerfile: deployments/docker/app/Dockerfile
    command: ["/usr/local/bin/compressfile", ]
    restart: always
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    expose:
      - ${APP_PORT}
    